# Generated by Django 3.1.1 on 2020-09-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClean',
        ),
    ]
